/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { BattleListEntry } from "./features/battle-list/state.js";
import { ChatMessage } from "./features/chat/state.js";
export { BattleListEntry } from "./features/battle-list/state.js";
export { ChatMessage } from "./features/chat/state.js";
export namespace Components {
    interface BattleList {
        /**
          * @default []
         */
        "entries": BattleListEntry[];
        /**
          * @default false
         */
        "ready": boolean;
    }
    interface ChatPanel {
        /**
          * @default false
         */
        "enabled": boolean;
        "focusInput": () => Promise<void>;
        /**
          * @default []
         */
        "messages": ChatMessage[];
        /**
          * @default false
         */
        "ready": boolean;
    }
    interface LoginModal {
        /**
          * @default null
         */
        "error": string | null;
        "focusInput": () => Promise<void>;
        /**
          * @default ""
         */
        "name": string;
        /**
          * @default true
         */
        "open": boolean;
        /**
          * @default true
         */
        "ready": boolean;
    }
}
export interface BattleListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBattleListElement;
}
export interface ChatPanelCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLChatPanelElement;
}
export interface LoginModalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLLoginModalElement;
}
declare global {
    interface HTMLBattleListElementEventMap {
        "ui:battle-list:attack": { targetId: number };
    }
    interface HTMLBattleListElement extends Components.BattleList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLBattleListElementEventMap>(type: K, listener: (this: HTMLBattleListElement, ev: BattleListCustomEvent<HTMLBattleListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLBattleListElementEventMap>(type: K, listener: (this: HTMLBattleListElement, ev: BattleListCustomEvent<HTMLBattleListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLBattleListElement: {
        prototype: HTMLBattleListElement;
        new (): HTMLBattleListElement;
    };
    interface HTMLChatPanelElementEventMap {
        "ui:chat:send": { message: string; type: number };
        "ui:chat:focus": { focused: boolean };
    }
    interface HTMLChatPanelElement extends Components.ChatPanel, HTMLStencilElement {
        addEventListener<K extends keyof HTMLChatPanelElementEventMap>(type: K, listener: (this: HTMLChatPanelElement, ev: ChatPanelCustomEvent<HTMLChatPanelElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLChatPanelElementEventMap>(type: K, listener: (this: HTMLChatPanelElement, ev: ChatPanelCustomEvent<HTMLChatPanelElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLChatPanelElement: {
        prototype: HTMLChatPanelElement;
        new (): HTMLChatPanelElement;
    };
    interface HTMLLoginModalElementEventMap {
        "ui:login:submit": { name: string };
        "ui:login:name": { name: string };
    }
    interface HTMLLoginModalElement extends Components.LoginModal, HTMLStencilElement {
        addEventListener<K extends keyof HTMLLoginModalElementEventMap>(type: K, listener: (this: HTMLLoginModalElement, ev: LoginModalCustomEvent<HTMLLoginModalElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLLoginModalElementEventMap>(type: K, listener: (this: HTMLLoginModalElement, ev: LoginModalCustomEvent<HTMLLoginModalElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLLoginModalElement: {
        prototype: HTMLLoginModalElement;
        new (): HTMLLoginModalElement;
    };
    interface HTMLElementTagNameMap {
        "battle-list": HTMLBattleListElement;
        "chat-panel": HTMLChatPanelElement;
        "login-modal": HTMLLoginModalElement;
    }
}
declare namespace LocalJSX {
    interface BattleList {
        /**
          * @default []
         */
        "entries"?: BattleListEntry[];
        "onUi:battle-list:attack"?: (event: BattleListCustomEvent<{ targetId: number }>) => void;
        /**
          * @default false
         */
        "ready"?: boolean;
    }
    interface ChatPanel {
        /**
          * @default false
         */
        "enabled"?: boolean;
        /**
          * @default []
         */
        "messages"?: ChatMessage[];
        "onUi:chat:focus"?: (event: ChatPanelCustomEvent<{ focused: boolean }>) => void;
        "onUi:chat:send"?: (event: ChatPanelCustomEvent<{ message: string; type: number }>) => void;
        /**
          * @default false
         */
        "ready"?: boolean;
    }
    interface LoginModal {
        /**
          * @default null
         */
        "error"?: string | null;
        /**
          * @default ""
         */
        "name"?: string;
        "onUi:login:name"?: (event: LoginModalCustomEvent<{ name: string }>) => void;
        "onUi:login:submit"?: (event: LoginModalCustomEvent<{ name: string }>) => void;
        /**
          * @default true
         */
        "open"?: boolean;
        /**
          * @default true
         */
        "ready"?: boolean;
    }

    interface BattleListAttributes {
        "ready": boolean;
    }
    interface ChatPanelAttributes {
        "enabled": boolean;
        "ready": boolean;
    }
    interface LoginModalAttributes {
        "open": boolean;
        "name": string;
        "error": string | null;
        "ready": boolean;
    }

    interface IntrinsicElements {
        "battle-list": Omit<BattleList, keyof BattleListAttributes> & { [K in keyof BattleList & keyof BattleListAttributes]?: BattleList[K] } & { [K in keyof BattleList & keyof BattleListAttributes as `attr:${K}`]?: BattleListAttributes[K] } & { [K in keyof BattleList & keyof BattleListAttributes as `prop:${K}`]?: BattleList[K] };
        "chat-panel": Omit<ChatPanel, keyof ChatPanelAttributes> & { [K in keyof ChatPanel & keyof ChatPanelAttributes]?: ChatPanel[K] } & { [K in keyof ChatPanel & keyof ChatPanelAttributes as `attr:${K}`]?: ChatPanelAttributes[K] } & { [K in keyof ChatPanel & keyof ChatPanelAttributes as `prop:${K}`]?: ChatPanel[K] };
        "login-modal": Omit<LoginModal, keyof LoginModalAttributes> & { [K in keyof LoginModal & keyof LoginModalAttributes]?: LoginModal[K] } & { [K in keyof LoginModal & keyof LoginModalAttributes as `attr:${K}`]?: LoginModalAttributes[K] } & { [K in keyof LoginModal & keyof LoginModalAttributes as `prop:${K}`]?: LoginModal[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "battle-list": LocalJSX.IntrinsicElements["battle-list"] & JSXBase.HTMLAttributes<HTMLBattleListElement>;
            "chat-panel": LocalJSX.IntrinsicElements["chat-panel"] & JSXBase.HTMLAttributes<HTMLChatPanelElement>;
            "login-modal": LocalJSX.IntrinsicElements["login-modal"] & JSXBase.HTMLAttributes<HTMLLoginModalElement>;
        }
    }
}
